#!/usr/bin/env python3
"""
Create the RTS Smart Covers Home Assistant HACS custom integration project.

This v4 generator targets Home Assistant 2026.6.1+ style custom integrations:
- local brand images under custom_components/rts_smart_covers/brand/
- config flow setup
- reconfigure flow instead of using options flow for setup data

Usage on Axel's Windows machine:

    cd "C:\\Users\\axelh\\Dropbox\\Axels mapp\\Coding Projects\\RTS-Smart-Covers"
    python create_rts_smart_covers_project.py --force
"""

from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_TARGET = Path(r"C:\Users\axelh\Dropbox\Axels mapp\Coding Projects\RTS-Smart-Covers")

FILES: dict[str, str] = {'.gitignore': '__pycache__/\n'
               '*.pyc\n'
               '*.pyo\n'
               '*.pyd\n'
               '.pytest_cache/\n'
               '.mypy_cache/\n'
               '.ruff_cache/\n'
               '.coverage\n'
               'htmlcov/\n'
               '.vscode/\n'
               '.idea/\n'
               '.DS_Store\n'
               'Thumbs.db\n'
               '.env\n'
               '.venv/\n'
               'venv/\n'
               'dist/\n'
               'build/\n'
               '*.egg-info/\n',
 'LICENSE': 'MIT License\n'
            '\n'
            'Copyright (c) 2026 Axel Holmstedt\n'
            '\n'
            'Permission is hereby granted, free of charge, to any person obtaining a copy\n'
            'of this software and associated documentation files (the "Software"), to deal\n'
            'in the Software without restriction, including without limitation the rights\n'
            'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n'
            'copies of the Software, and to permit persons to whom the Software is\n'
            'furnished to do so, subject to the following conditions:\n'
            '\n'
            'The above copyright notice and this permission notice shall be included in all\n'
            'copies or substantial portions of the Software.\n'
            '\n'
            'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n'
            'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n'
            'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n'
            'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n'
            'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n'
            'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n'
            'SOFTWARE.\n',
 'README.md': '# RTS Smart Covers\n'
              '\n'
              'RTS Smart Covers is a Home Assistant custom integration for covers that only support `open`, `stop` and '
              '`close`, such as Somfy RTS covers controlled through RFXtrx.\n'
              '\n'
              'It creates a virtual smart cover with position support by estimating the position from the configured '
              'travel time.\n'
              '\n'
              '> Svenska: Projektet är byggt för Somfy RTS/RFXtrx-covers där man normalt bara har öppna, stoppa och '
              'stäng, men vill få en smart cover med procent-slider i Home Assistant.\n'
              '\n'
              '## Why this exists\n'
              '\n'
              'Somfy RTS via RFXtrx usually has no real position feedback. Home Assistant can send commands, but it '
              'cannot know the true position of the cover.\n'
              '\n'
              'This integration solves that by keeping an assumed position in software:\n'
              '\n'
              '- `0%` = fully closed\n'
              '- `100%` = fully open\n'
              '- `30%` = 30% open and 70% closed\n'
              '\n'
              'The integration sends `open` or `close`, waits for the calculated duration, then sends `stop`.\n'
              '\n'
              '## Example\n'
              '\n'
              'Source cover:\n'
              '\n'
              '```text\n'
              'cover.officesoversleft2\n'
              '```\n'
              '\n'
              'Travel time:\n'
              '\n'
              '```text\n'
              '35 seconds\n'
              '```\n'
              '\n'
              'If the smart cover is assumed to be at `100%` and you set it to `30%`, it will:\n'
              '\n'
              '1. send `cover.close_cover` to the source cover\n'
              '2. wait about `24.5 seconds`\n'
              '3. send `cover.stop_cover`\n'
              '\n'
              'Because:\n'
              '\n'
              '```text\n'
              '100% - 30% = 70%\n'
              '70% of 35 seconds = 24.5 seconds\n'
              '```\n'
              '\n'
              'If it is assumed to be at `0%` and you set it to `30%`, it will:\n'
              '\n'
              '1. send `cover.open_cover`\n'
              '2. wait about `10.5 seconds`\n'
              '3. send `cover.stop_cover`\n'
              '\n'
              'Because:\n'
              '\n'
              '```text\n'
              '30% of 35 seconds = 10.5 seconds\n'
              '```\n'
              '\n'
              '## Features\n'
              '\n'
              '- Creates a new virtual `cover` entity.\n'
              '- Supports open, close, stop and set position.\n'
              '- Works with the standard Home Assistant cover slider.\n'
              '- Estimates position based on travel time.\n'
              '- Restores the last assumed position after Home Assistant restart.\n'
              '- Updates the cover position while moving so the UI feels responsive.\n'
              '- Supports multiple smart covers, one config entry per source cover.\n'
              '- Does not require YAML helpers, scripts, automations, timers or template covers.\n'
              '\n'
              '## Reconfigure\n'
              '\n'
              "After setup, use the integration's **Reconfigure** action from Home Assistant's integration page to "
              'change the source cover, smart cover name, travel time or initial assumed position.\n'
              '\n'
              '## Important limitation\n'
              '\n'
              'The position is estimated, not measured.\n'
              '\n'
              'RTS/RFXtrx does not normally report exact cover position. If someone uses the physical remote or '
              'another integration outside RTS Smart Covers, the assumed position can become wrong.\n'
              '\n'
              'Best practice:\n'
              '\n'
              '- Control the cover through the new smart cover entity.\n'
              '- Occasionally recalibrate by moving fully open or fully closed and setting the initial '
              'position/options accordingly.\n'
              '\n'
              '## Installation via HACS custom repository\n'
              '\n'
              '1. Push this repository to GitHub.\n'
              '2. In Home Assistant, open HACS.\n'
              '3. Open the menu with the three dots.\n'
              '4. Select **Custom repositories**.\n'
              '5. Add:\n'
              '\n'
              '```text\n'
              'https://github.com/haxxel1337/RTS-Smart-Covers\n'
              '```\n'
              '\n'
              '6. Select type:\n'
              '\n'
              '```text\n'
              'Integration\n'
              '```\n'
              '\n'
              '7. Install **RTS Smart Covers**.\n'
              '8. Restart Home Assistant.\n'
              '\n'
              '## Manual installation\n'
              '\n'
              'Copy this folder:\n'
              '\n'
              '```text\n'
              'custom_components/rts_smart_covers\n'
              '```\n'
              '\n'
              'to your Home Assistant config folder:\n'
              '\n'
              '```text\n'
              '/config/custom_components/rts_smart_covers\n'
              '```\n'
              '\n'
              'Restart Home Assistant.\n'
              '\n'
              '## Configuration\n'
              '\n'
              'Go to:\n'
              '\n'
              '```text\n'
              'Settings -> Devices & Services -> Add Integration -> RTS Smart Covers\n'
              '```\n'
              '\n'
              'Fill in:\n'
              '\n'
              '| Field | Example |\n'
              '|---|---|\n'
              '| Source cover | `cover.officesoversleft2` |\n'
              '| Smart cover name | `Office Covers Left Smart` |\n'
              '| Full travel time | `35` |\n'
              '| Initial assumed position | `100` |\n'
              '\n'
              'After setup, Home Assistant creates a new smart cover entity, for example:\n'
              '\n'
              '```text\n'
              'cover.office_covers_left_smart\n'
              '```\n'
              '\n'
              'Use this new smart cover in dashboards, automations and Mushroom cards.\n'
              '\n'
              '## Testing from Developer Tools\n'
              '\n'
              'Go to:\n'
              '\n'
              '```text\n'
              'Developer Tools -> Actions\n'
              '```\n'
              '\n'
              'Run:\n'
              '\n'
              '```yaml\n'
              'action: cover.set_cover_position\n'
              'target:\n'
              '  entity_id: cover.office_covers_left_smart\n'
              'data:\n'
              '  position: 30\n'
              '```\n'
              '\n'
              'Expected result from fully open with 35 second travel time:\n'
              '\n'
              '```text\n'
              'close for about 24.5 seconds, then stop\n'
              '```\n'
              '\n'
              '## Mushroom card example\n'
              '\n'
              '```yaml\n'
              'type: custom:mushroom-cover-card\n'
              'entity: cover.office_covers_left_smart\n'
              'name: Office Covers Left\n'
              'show_position_control: true\n'
              'show_buttons_control: true\n'
              'fill_container: true\n'
              'layout: vertical\n'
              '```\n'
              '\n'
              '## Branding\n'
              '\n'
              'For Home Assistant 2026.3 and newer, custom integrations can ship local brand images inside their own '
              'integration directory.\n'
              '\n'
              'This integration includes a `brand` folder inside `custom_components/rts_smart_covers`.\n'
              '\n'
              'Place these files there:\n'
              '\n'
              '```text\n'
              'custom_components/rts_smart_covers/brand/logo.png\n'
              'custom_components/rts_smart_covers/brand/icon.png\n'
              '```\n'
              '\n'
              'These are for your own project/repository branding. The integration itself does not require them to '
              'run.\n'
              '\n'
              '## Development notes\n'
              '\n'
              'Project domain:\n'
              '\n'
              '```text\n'
              'rts_smart_covers\n'
              '```\n'
              '\n'
              'Integration folder:\n'
              '\n'
              '```text\n'
              'custom_components/rts_smart_covers\n'
              '```\n'
              '\n'
              'GitHub repository:\n'
              '\n'
              '```text\n'
              'haxxel1337/RTS-Smart-Covers\n'
              '```\n'
              '\n'
              '## License\n'
              '\n'
              'MIT\n',
 'custom_components/rts_smart_covers/__init__.py': '"""RTS Smart Covers custom integration."""\n'
                                                   'from __future__ import annotations\n'
                                                   '\n'
                                                   'from homeassistant.config_entries import ConfigEntry\n'
                                                   'from homeassistant.core import HomeAssistant\n'
                                                   '\n'
                                                   'from .const import PLATFORMS\n'
                                                   '\n'
                                                   '\n'
                                                   'async def async_setup_entry(hass: HomeAssistant, entry: '
                                                   'ConfigEntry) -> bool:\n'
                                                   '    """Set up RTS Smart Covers from a config entry."""\n'
                                                   '    await hass.config_entries.async_forward_entry_setups(entry, '
                                                   'PLATFORMS)\n'
                                                   '    return True\n'
                                                   '\n'
                                                   '\n'
                                                   'async def async_unload_entry(hass: HomeAssistant, entry: '
                                                   'ConfigEntry) -> bool:\n'
                                                   '    """Unload a config entry."""\n'
                                                   '    return await hass.config_entries.async_unload_platforms(entry, '
                                                   'PLATFORMS)\n',
 'custom_components/rts_smart_covers/brand/.gitkeep': '',
 'custom_components/rts_smart_covers/config_flow.py': '"""Config flow for RTS Smart Covers."""\n'
                                                      'from __future__ import annotations\n'
                                                      '\n'
                                                      'from typing import Any\n'
                                                      '\n'
                                                      'import voluptuous as vol\n'
                                                      '\n'
                                                      'from homeassistant import config_entries\n'
                                                      'from homeassistant.const import CONF_NAME\n'
                                                      'from homeassistant.helpers import selector\n'
                                                      '\n'
                                                      'from .const import (\n'
                                                      '    CONF_INITIAL_POSITION,\n'
                                                      '    CONF_SOURCE_COVER,\n'
                                                      '    CONF_TRAVEL_TIME,\n'
                                                      '    DEFAULT_INITIAL_POSITION,\n'
                                                      '    DEFAULT_NAME,\n'
                                                      '    DEFAULT_TRAVEL_TIME,\n'
                                                      '    DOMAIN,\n'
                                                      '    MAX_TRAVEL_TIME,\n'
                                                      '    MIN_TRAVEL_TIME,\n'
                                                      ')\n'
                                                      '\n'
                                                      '\n'
                                                      'def _build_schema(defaults: dict[str, Any] | None = None) -> '
                                                      'vol.Schema:\n'
                                                      '    """Build the config/reconfigure form schema."""\n'
                                                      '    defaults = defaults or {}\n'
                                                      '\n'
                                                      '    return vol.Schema(\n'
                                                      '        {\n'
                                                      '            vol.Required(\n'
                                                      '                CONF_SOURCE_COVER,\n'
                                                      '                default=defaults.get(CONF_SOURCE_COVER),\n'
                                                      '            ): selector.EntitySelector(\n'
                                                      '                selector.EntitySelectorConfig(domain="cover")\n'
                                                      '            ),\n'
                                                      '            vol.Required(\n'
                                                      '                CONF_NAME,\n'
                                                      '                default=defaults.get(CONF_NAME, DEFAULT_NAME),\n'
                                                      '            ): selector.TextSelector(),\n'
                                                      '            vol.Required(\n'
                                                      '                CONF_TRAVEL_TIME,\n'
                                                      '                default=defaults.get(CONF_TRAVEL_TIME, '
                                                      'DEFAULT_TRAVEL_TIME),\n'
                                                      '            ): selector.NumberSelector(\n'
                                                      '                selector.NumberSelectorConfig(\n'
                                                      '                    min=MIN_TRAVEL_TIME,\n'
                                                      '                    max=MAX_TRAVEL_TIME,\n'
                                                      '                    step=0.5,\n'
                                                      '                    mode=selector.NumberSelectorMode.BOX,\n'
                                                      '                    unit_of_measurement="s",\n'
                                                      '                )\n'
                                                      '            ),\n'
                                                      '            vol.Required(\n'
                                                      '                CONF_INITIAL_POSITION,\n'
                                                      '                default=defaults.get(CONF_INITIAL_POSITION, '
                                                      'DEFAULT_INITIAL_POSITION),\n'
                                                      '            ): selector.NumberSelector(\n'
                                                      '                selector.NumberSelectorConfig(\n'
                                                      '                    min=0,\n'
                                                      '                    max=100,\n'
                                                      '                    step=1,\n'
                                                      '                    mode=selector.NumberSelectorMode.SLIDER,\n'
                                                      '                    unit_of_measurement="%",\n'
                                                      '                )\n'
                                                      '            ),\n'
                                                      '        }\n'
                                                      '    )\n'
                                                      '\n'
                                                      '\n'
                                                      'class RtsSmartCoversConfigFlow(config_entries.ConfigFlow, '
                                                      'domain=DOMAIN):\n'
                                                      '    """Handle a config flow for RTS Smart Covers."""\n'
                                                      '\n'
                                                      '    VERSION = 1\n'
                                                      '    MINOR_VERSION = 1\n'
                                                      '\n'
                                                      '    async def async_step_user(\n'
                                                      '        self,\n'
                                                      '        user_input: dict[str, Any] | None = None,\n'
                                                      '    ) -> config_entries.ConfigFlowResult:\n'
                                                      '        """Handle a user-initiated setup flow."""\n'
                                                      '        if user_input is not None:\n'
                                                      '            source_cover = user_input[CONF_SOURCE_COVER]\n'
                                                      '\n'
                                                      '            await self.async_set_unique_id(source_cover)\n'
                                                      '            self._abort_if_unique_id_configured()\n'
                                                      '\n'
                                                      '            return self.async_create_entry(\n'
                                                      '                title=user_input[CONF_NAME],\n'
                                                      '                data=user_input,\n'
                                                      '            )\n'
                                                      '\n'
                                                      '        return self.async_show_form(\n'
                                                      '            step_id="user",\n'
                                                      '            data_schema=_build_schema(),\n'
                                                      '            errors={},\n'
                                                      '        )\n'
                                                      '\n'
                                                      '    async def async_step_reconfigure(\n'
                                                      '        self,\n'
                                                      '        user_input: dict[str, Any] | None = None,\n'
                                                      '    ) -> config_entries.ConfigFlowResult:\n'
                                                      '        """Handle reconfiguration from the integration settings '
                                                      'page."""\n'
                                                      '        config_entry = self._get_reconfigure_entry()\n'
                                                      '\n'
                                                      '        if user_input is not None:\n'
                                                      '            source_cover = user_input[CONF_SOURCE_COVER]\n'
                                                      '\n'
                                                      '            await self.async_set_unique_id(source_cover)\n'
                                                      '            self._abort_if_unique_id_mismatch()\n'
                                                      '\n'
                                                      '            return self.async_update_reload_and_abort(\n'
                                                      '                config_entry,\n'
                                                      '                data_updates=user_input,\n'
                                                      '            )\n'
                                                      '\n'
                                                      '        defaults = dict(config_entry.data)\n'
                                                      '\n'
                                                      '        return self.async_show_form(\n'
                                                      '            step_id="reconfigure",\n'
                                                      '            data_schema=_build_schema(defaults),\n'
                                                      '            errors={},\n'
                                                      '        )\n',
 'custom_components/rts_smart_covers/const.py': '"""Constants for RTS Smart Covers."""\n'
                                                'from __future__ import annotations\n'
                                                '\n'
                                                'from homeassistant.const import Platform\n'
                                                '\n'
                                                'DOMAIN = "rts_smart_covers"\n'
                                                'PLATFORMS = [Platform.COVER]\n'
                                                '\n'
                                                'CONF_SOURCE_COVER = "source_cover"\n'
                                                'CONF_TRAVEL_TIME = "travel_time"\n'
                                                'CONF_INITIAL_POSITION = "initial_position"\n'
                                                '\n'
                                                'DEFAULT_NAME = "RTS Smart Cover"\n'
                                                'DEFAULT_TRAVEL_TIME = 35.0\n'
                                                'DEFAULT_INITIAL_POSITION = 100\n'
                                                '\n'
                                                'MIN_TRAVEL_TIME = 1.0\n'
                                                'MAX_TRAVEL_TIME = 300.0\n',
 'custom_components/rts_smart_covers/cover.py': '"""Cover platform for RTS Smart Covers."""\n'
                                                'from __future__ import annotations\n'
                                                '\n'
                                                'import logging\n'
                                                'from time import monotonic\n'
                                                'from typing import Any\n'
                                                '\n'
                                                'from homeassistant.components.cover import (\n'
                                                '    ATTR_POSITION,\n'
                                                '    CoverDeviceClass,\n'
                                                '    CoverEntity,\n'
                                                '    CoverEntityFeature,\n'
                                                ')\n'
                                                'from homeassistant.config_entries import ConfigEntry\n'
                                                'from homeassistant.const import (\n'
                                                '    CONF_NAME,\n'
                                                '    SERVICE_CLOSE_COVER,\n'
                                                '    SERVICE_OPEN_COVER,\n'
                                                '    SERVICE_STOP_COVER,\n'
                                                '    STATE_UNAVAILABLE,\n'
                                                '    STATE_UNKNOWN,\n'
                                                ')\n'
                                                'from homeassistant.core import HomeAssistant, callback\n'
                                                'from homeassistant.helpers.entity_platform import '
                                                'AddEntitiesCallback\n'
                                                'from homeassistant.helpers.event import async_call_later\n'
                                                'from homeassistant.helpers.restore_state import RestoreEntity\n'
                                                '\n'
                                                'from .const import (\n'
                                                '    CONF_INITIAL_POSITION,\n'
                                                '    CONF_SOURCE_COVER,\n'
                                                '    CONF_TRAVEL_TIME,\n'
                                                '    DEFAULT_INITIAL_POSITION,\n'
                                                '    DEFAULT_NAME,\n'
                                                '    DEFAULT_TRAVEL_TIME,\n'
                                                ')\n'
                                                '\n'
                                                '_LOGGER = logging.getLogger(__name__)\n'
                                                '\n'
                                                '\n'
                                                'async def async_setup_entry(\n'
                                                '    hass: HomeAssistant,\n'
                                                '    entry: ConfigEntry,\n'
                                                '    async_add_entities: AddEntitiesCallback,\n'
                                                ') -> None:\n'
                                                '    """Set up RTS Smart Covers entities."""\n'
                                                '    async_add_entities([RtsSmartCoverEntity(hass, entry)])\n'
                                                '\n'
                                                '\n'
                                                'class RtsSmartCoverEntity(CoverEntity, RestoreEntity):\n'
                                                '    """Time-estimated cover built on top of an open/stop/close RTS '
                                                'cover."""\n'
                                                '\n'
                                                '    _attr_assumed_state = True\n'
                                                '    _attr_device_class = CoverDeviceClass.SHADE\n'
                                                '    _attr_has_entity_name = False\n'
                                                '    _attr_should_poll = False\n'
                                                '    _attr_supported_features = (\n'
                                                '        CoverEntityFeature.OPEN\n'
                                                '        | CoverEntityFeature.CLOSE\n'
                                                '        | CoverEntityFeature.STOP\n'
                                                '        | CoverEntityFeature.SET_POSITION\n'
                                                '    )\n'
                                                '\n'
                                                '    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> '
                                                'None:\n'
                                                '        """Initialize the smart cover."""\n'
                                                '        self.hass = hass\n'
                                                '        self.entry = entry\n'
                                                '\n'
                                                '        data = {**entry.data, **entry.options}\n'
                                                '\n'
                                                '        self._source_cover: str = data[CONF_SOURCE_COVER]\n'
                                                '        self._travel_time: float = float(data.get(CONF_TRAVEL_TIME, '
                                                'DEFAULT_TRAVEL_TIME))\n'
                                                '        self._position: float = self._clamp(\n'
                                                '            float(data.get(CONF_INITIAL_POSITION, '
                                                'DEFAULT_INITIAL_POSITION))\n'
                                                '        )\n'
                                                '\n'
                                                '        self._attr_name = data.get(CONF_NAME, DEFAULT_NAME)\n'
                                                '        self._attr_unique_id = f"{entry.entry_id}_rts_smart_cover"\n'
                                                '\n'
                                                '        self._direction: str | None = None\n'
                                                '        self._target_position: float | None = None\n'
                                                '        self._started_position: float = self._position\n'
                                                '        self._started_at: float | None = None\n'
                                                '\n'
                                                '        self._auto_stop_unsub = None\n'
                                                '        self._tick_unsub = None\n'
                                                '\n'
                                                '\n'
                                                '    async def async_will_remove_from_hass(self) -> None:\n'
                                                '        """Cancel pending timers when Home Assistant removes the '
                                                'entity."""\n'
                                                '        self._clear_timers()\n'
                                                '\n'
                                                '    async def async_added_to_hass(self) -> None:\n'
                                                '        """Restore the last assumed position after Home Assistant '
                                                'restart."""\n'
                                                '        last_state = await self.async_get_last_state()\n'
                                                '        if last_state is None:\n'
                                                '            return\n'
                                                '\n'
                                                '        restored_position = '
                                                'last_state.attributes.get("current_position")\n'
                                                '\n'
                                                '        if restored_position is None:\n'
                                                '            if last_state.state == "closed":\n'
                                                '                restored_position = 0\n'
                                                '            elif last_state.state == "open":\n'
                                                '                restored_position = 100\n'
                                                '\n'
                                                '        if restored_position is None:\n'
                                                '            return\n'
                                                '\n'
                                                '        try:\n'
                                                '            self._position = self._clamp(float(restored_position))\n'
                                                '            _LOGGER.debug(\n'
                                                '                "Restored %s assumed position to %.1f",\n'
                                                '                self.entity_id,\n'
                                                '                self._position,\n'
                                                '            )\n'
                                                '        except (TypeError, ValueError):\n'
                                                '            _LOGGER.debug("Could not restore position from %r", '
                                                'restored_position)\n'
                                                '\n'
                                                '    @property\n'
                                                '    def available(self) -> bool:\n'
                                                '        """Return whether the source cover is available."""\n'
                                                '        source_state = self.hass.states.get(self._source_cover)\n'
                                                '        return source_state is not None and source_state.state not in '
                                                '{\n'
                                                '            STATE_UNAVAILABLE,\n'
                                                '            STATE_UNKNOWN,\n'
                                                '        }\n'
                                                '\n'
                                                '    @property\n'
                                                '    def current_cover_position(self) -> int:\n'
                                                '        """Return current estimated position, where 0 is closed and '
                                                '100 is open."""\n'
                                                '        return round(self._estimated_position())\n'
                                                '\n'
                                                '    @property\n'
                                                '    def is_closed(self) -> bool:\n'
                                                '        """Return true if the cover is fully closed."""\n'
                                                '        return self.current_cover_position <= 0\n'
                                                '\n'
                                                '    @property\n'
                                                '    def is_opening(self) -> bool:\n'
                                                '        """Return true if the cover is opening."""\n'
                                                '        return self._direction == "opening"\n'
                                                '\n'
                                                '    @property\n'
                                                '    def is_closing(self) -> bool:\n'
                                                '        """Return true if the cover is closing."""\n'
                                                '        return self._direction == "closing"\n'
                                                '\n'
                                                '    @property\n'
                                                '    def extra_state_attributes(self) -> dict[str, Any]:\n'
                                                '        """Return extra state attributes."""\n'
                                                '        return {\n'
                                                '            "source_cover": self._source_cover,\n'
                                                '            "travel_time": self._travel_time,\n'
                                                '            "target_position": self._target_position,\n'
                                                '            "assumed_position": True,\n'
                                                '        }\n'
                                                '\n'
                                                '    async def async_open_cover(self, **kwargs: Any) -> None:\n'
                                                '        """Open the cover fully."""\n'
                                                '        await self._async_move_to(100)\n'
                                                '\n'
                                                '    async def async_close_cover(self, **kwargs: Any) -> None:\n'
                                                '        """Close the cover fully."""\n'
                                                '        await self._async_move_to(0)\n'
                                                '\n'
                                                '    async def async_set_cover_position(self, **kwargs: Any) -> None:\n'
                                                '        """Move the cover to the requested position."""\n'
                                                '        position = kwargs.get(ATTR_POSITION)\n'
                                                '        if position is None:\n'
                                                '            return\n'
                                                '\n'
                                                '        await self._async_move_to(float(position))\n'
                                                '\n'
                                                '    async def async_stop_cover(self, **kwargs: Any) -> None:\n'
                                                '        """Stop the cover and store the current estimated '
                                                'position."""\n'
                                                '        await self._async_stop_and_store(send_stop=True)\n'
                                                '\n'
                                                '    async def _async_move_to(self, target_position: float) -> None:\n'
                                                '        """Move the cover to a position by timing open/close then '
                                                'sending stop."""\n'
                                                '        target_position = self._clamp(target_position)\n'
                                                '\n'
                                                '        if self._direction is not None:\n'
                                                '            await self._async_stop_and_store(send_stop=True)\n'
                                                '\n'
                                                '        current_position = self._clamp(self._position)\n'
                                                '        difference = target_position - current_position\n'
                                                '\n'
                                                '        if abs(difference) < 0.5:\n'
                                                '            self._position = target_position\n'
                                                '            self._direction = None\n'
                                                '            self._target_position = None\n'
                                                '            self._started_at = None\n'
                                                '            self.async_write_ha_state()\n'
                                                '            return\n'
                                                '\n'
                                                '        duration = abs(difference) / 100 * self._travel_time\n'
                                                '\n'
                                                '        self._direction = "opening" if difference > 0 else "closing"\n'
                                                '        self._target_position = target_position\n'
                                                '        self._started_position = current_position\n'
                                                '        self._started_at = monotonic()\n'
                                                '\n'
                                                '        service = SERVICE_OPEN_COVER if self._direction == "opening" '
                                                'else SERVICE_CLOSE_COVER\n'
                                                '\n'
                                                '        _LOGGER.debug(\n'
                                                '            "%s moving from %.1f to %.1f using %s for %.2fs",\n'
                                                '            self.entity_id,\n'
                                                '            current_position,\n'
                                                '            target_position,\n'
                                                '            service,\n'
                                                '            duration,\n'
                                                '        )\n'
                                                '\n'
                                                '        self.async_write_ha_state()\n'
                                                '        await self._async_source_call(service)\n'
                                                '\n'
                                                '        @callback\n'
                                                '        def _auto_stop_callback(_now) -> None:\n'
                                                '            '
                                                'self.hass.async_create_task(self._async_finish_move(target_position))\n'
                                                '\n'
                                                '        self._auto_stop_unsub = async_call_later(\n'
                                                '            self.hass,\n'
                                                '            duration,\n'
                                                '            _auto_stop_callback,\n'
                                                '        )\n'
                                                '        self._schedule_tick()\n'
                                                '\n'
                                                '    async def _async_finish_move(self, target_position: float) -> '
                                                'None:\n'
                                                '        """Finish timed movement and stop at the target position."""\n'
                                                '        self._position = self._clamp(target_position)\n'
                                                '        self._clear_timers()\n'
                                                '\n'
                                                '        await self._async_source_call(SERVICE_STOP_COVER)\n'
                                                '\n'
                                                '        _LOGGER.debug("%s reached target %.1f", self.entity_id, '
                                                'self._position)\n'
                                                '\n'
                                                '        self._direction = None\n'
                                                '        self._target_position = None\n'
                                                '        self._started_at = None\n'
                                                '\n'
                                                '        self.async_write_ha_state()\n'
                                                '\n'
                                                '    async def _async_stop_and_store(self, *, send_stop: bool) -> '
                                                'None:\n'
                                                '        """Stop movement, store the current estimated position, and '
                                                'clear timers."""\n'
                                                '        self._position = self._estimated_position()\n'
                                                '        was_moving = self._direction is not None\n'
                                                '\n'
                                                '        self._clear_timers()\n'
                                                '\n'
                                                '        if send_stop and was_moving:\n'
                                                '            await self._async_source_call(SERVICE_STOP_COVER)\n'
                                                '\n'
                                                '        _LOGGER.debug(\n'
                                                '            "%s stopped at estimated position %.1f",\n'
                                                '            self.entity_id,\n'
                                                '            self._position,\n'
                                                '        )\n'
                                                '\n'
                                                '        self._direction = None\n'
                                                '        self._target_position = None\n'
                                                '        self._started_at = None\n'
                                                '\n'
                                                '        self.async_write_ha_state()\n'
                                                '\n'
                                                '    async def _async_source_call(self, service: str) -> None:\n'
                                                '        """Call a cover service on the source cover."""\n'
                                                '        await self.hass.services.async_call(\n'
                                                '            "cover",\n'
                                                '            service,\n'
                                                '            {"entity_id": self._source_cover},\n'
                                                '            blocking=True,\n'
                                                '        )\n'
                                                '\n'
                                                '    def _estimated_position(self) -> float:\n'
                                                '        """Return the current estimated position."""\n'
                                                '        if self._direction is None or self._started_at is None:\n'
                                                '            return self._clamp(self._position)\n'
                                                '\n'
                                                '        elapsed = max(0.0, monotonic() - self._started_at)\n'
                                                '        moved_pct = elapsed / self._travel_time * 100\n'
                                                '\n'
                                                '        if self._direction == "opening":\n'
                                                '            return self._clamp(self._started_position + moved_pct)\n'
                                                '\n'
                                                '        return self._clamp(self._started_position - moved_pct)\n'
                                                '\n'
                                                '    def _schedule_tick(self) -> None:\n'
                                                '        """Update Home Assistant state once per second while '
                                                'moving."""\n'
                                                '        self._cancel_tick_timer()\n'
                                                '\n'
                                                '        @callback\n'
                                                '        def _tick(_now) -> None:\n'
                                                '            self._tick_unsub = None\n'
                                                '\n'
                                                '            if self._direction is None:\n'
                                                '                return\n'
                                                '\n'
                                                '            self.async_write_ha_state()\n'
                                                '            self._schedule_tick()\n'
                                                '\n'
                                                '        self._tick_unsub = async_call_later(self.hass, 1, _tick)\n'
                                                '\n'
                                                '    def _clear_timers(self) -> None:\n'
                                                '        """Cancel all timers."""\n'
                                                '        self._cancel_auto_stop_timer()\n'
                                                '        self._cancel_tick_timer()\n'
                                                '\n'
                                                '    def _cancel_auto_stop_timer(self) -> None:\n'
                                                '        """Cancel the pending auto-stop timer."""\n'
                                                '        if self._auto_stop_unsub is not None:\n'
                                                '            self._auto_stop_unsub()\n'
                                                '            self._auto_stop_unsub = None\n'
                                                '\n'
                                                '    def _cancel_tick_timer(self) -> None:\n'
                                                '        """Cancel the UI tick timer."""\n'
                                                '        if self._tick_unsub is not None:\n'
                                                '            self._tick_unsub()\n'
                                                '            self._tick_unsub = None\n'
                                                '\n'
                                                '    @staticmethod\n'
                                                '    def _clamp(value: float) -> float:\n'
                                                '        """Clamp a cover position to the Home Assistant 0-100 '
                                                'range."""\n'
                                                '        return max(0.0, min(100.0, value))\n',
 'custom_components/rts_smart_covers/manifest.json': '{\n'
                                                     '  "domain": "rts_smart_covers",\n'
                                                     '  "name": "RTS Smart Covers",\n'
                                                     '  "codeowners": [\n'
                                                     '    "@haxxel1337"\n'
                                                     '  ],\n'
                                                     '  "config_flow": true,\n'
                                                     '  "documentation": '
                                                     '"https://github.com/haxxel1337/RTS-Smart-Covers",\n'
                                                     '  "issue_tracker": '
                                                     '"https://github.com/haxxel1337/RTS-Smart-Covers/issues",\n'
                                                     '  "iot_class": "local_push",\n'
                                                     '  "version": "0.1.0"\n'
                                                     '}\n',
 'custom_components/rts_smart_covers/strings.json': '{\n'
                                                    '  "title": "RTS Smart Covers",\n'
                                                    '  "config": {\n'
                                                    '    "step": {\n'
                                                    '      "user": {\n'
                                                    '        "title": "Create RTS smart cover",\n'
                                                    '        "description": "Create a virtual position cover from an '
                                                    'RTS/RFXtrx cover that only supports open, stop and close.",\n'
                                                    '        "data": {\n'
                                                    '          "source_cover": "Source cover",\n'
                                                    '          "name": "Smart cover name",\n'
                                                    '          "travel_time": "Full travel time",\n'
                                                    '          "initial_position": "Initial assumed position"\n'
                                                    '        }\n'
                                                    '      },\n'
                                                    '      "reconfigure": {\n'
                                                    '        "title": "Reconfigure RTS smart cover",\n'
                                                    '        "description": "Update the source cover, smart cover '
                                                    'name, travel time or initial assumed position.",\n'
                                                    '        "data": {\n'
                                                    '          "source_cover": "Source cover",\n'
                                                    '          "name": "Smart cover name",\n'
                                                    '          "travel_time": "Full travel time",\n'
                                                    '          "initial_position": "Initial assumed position"\n'
                                                    '        }\n'
                                                    '      }\n'
                                                    '    },\n'
                                                    '    "abort": {\n'
                                                    '      "already_configured": "This source cover is already '
                                                    'configured.",\n'
                                                    '      "reconfigure_successful": "RTS Smart Covers was '
                                                    'reconfigured successfully."\n'
                                                    '    }\n'
                                                    '  }\n'
                                                    '}\n',
 'custom_components/rts_smart_covers/translations/en.json': '{\n'
                                                            '  "title": "RTS Smart Covers",\n'
                                                            '  "config": {\n'
                                                            '    "step": {\n'
                                                            '      "user": {\n'
                                                            '        "title": "Create RTS smart cover",\n'
                                                            '        "description": "Create a virtual position cover '
                                                            'from an RTS/RFXtrx cover that only supports open, stop '
                                                            'and close.",\n'
                                                            '        "data": {\n'
                                                            '          "source_cover": "Source cover",\n'
                                                            '          "name": "Smart cover name",\n'
                                                            '          "travel_time": "Full travel time",\n'
                                                            '          "initial_position": "Initial assumed position"\n'
                                                            '        }\n'
                                                            '      },\n'
                                                            '      "reconfigure": {\n'
                                                            '        "title": "Reconfigure RTS smart cover",\n'
                                                            '        "description": "Update the source cover, smart '
                                                            'cover name, travel time or initial assumed position.",\n'
                                                            '        "data": {\n'
                                                            '          "source_cover": "Source cover",\n'
                                                            '          "name": "Smart cover name",\n'
                                                            '          "travel_time": "Full travel time",\n'
                                                            '          "initial_position": "Initial assumed position"\n'
                                                            '        }\n'
                                                            '      }\n'
                                                            '    },\n'
                                                            '    "abort": {\n'
                                                            '      "already_configured": "This source cover is already '
                                                            'configured.",\n'
                                                            '      "reconfigure_successful": "RTS Smart Covers was '
                                                            'reconfigured successfully."\n'
                                                            '    }\n'
                                                            '  }\n'
                                                            '}\n',
 'custom_components/rts_smart_covers/translations/sv.json': '{\n'
                                                            '  "title": "RTS Smart Covers",\n'
                                                            '  "config": {\n'
                                                            '    "step": {\n'
                                                            '      "user": {\n'
                                                            '        "title": "Skapa RTS smart cover",\n'
                                                            '        "description": "Skapa en virtuell positions-cover '
                                                            'från en RTS/RFXtrx-cover som bara stöder öppna, stoppa '
                                                            'och stäng.",\n'
                                                            '        "data": {\n'
                                                            '          "source_cover": "Käll-cover",\n'
                                                            '          "name": "Namn på smart cover",\n'
                                                            '          "travel_time": "Full gångtid",\n'
                                                            '          "initial_position": "Initial antagen position"\n'
                                                            '        }\n'
                                                            '      },\n'
                                                            '      "reconfigure": {\n'
                                                            '        "title": "Konfigurera om RTS smart cover",\n'
                                                            '        "description": "Uppdatera käll-cover, namn på '
                                                            'smart cover, gångtid eller initial antagen position.",\n'
                                                            '        "data": {\n'
                                                            '          "source_cover": "Käll-cover",\n'
                                                            '          "name": "Namn på smart cover",\n'
                                                            '          "travel_time": "Full gångtid",\n'
                                                            '          "initial_position": "Initial antagen position"\n'
                                                            '        }\n'
                                                            '      }\n'
                                                            '    },\n'
                                                            '    "abort": {\n'
                                                            '      "already_configured": "Den här käll-covern är redan '
                                                            'konfigurerad.",\n'
                                                            '      "reconfigure_successful": "RTS Smart Covers '
                                                            'konfigurerades om."\n'
                                                            '    }\n'
                                                            '  }\n'
                                                            '}\n',
 'hacs.json': '{\n'
              '  "name": "RTS Smart Covers",\n'
              '  "render_readme": true,\n'
              '  "domains": [\n'
              '    "cover"\n'
              '  ],\n'
              '  "homeassistant": "2026.6.1"\n'
              '}\n'}


def write_file(path: Path, content: str, *, force: bool) -> str:
    """Write a file and return the action that was taken."""
    if path.exists() and not force:
        return "skipped"

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return "written"


def main() -> int:
    """Create the project."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--target",
        type=Path,
        default=None,
        help="Target project folder. Defaults to current folder if run inside RTS-Smart-Covers, otherwise Axel's default path.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files.",
    )
    args = parser.parse_args()

    current = Path.cwd()
    if args.target is not None:
        target = args.target
    elif current.name == "RTS-Smart-Covers":
        target = current
    else:
        target = DEFAULT_TARGET

    target.mkdir(parents=True, exist_ok=True)

    print("Creating RTS Smart Covers project in:")
    print(f"  {target}")
    print()

    written = 0
    skipped = 0

    for relative_path, content in FILES.items():
        destination = target / relative_path
        action = write_file(destination, content, force=args.force)

        if action == "written":
            written += 1
            print(f"[WRITE] {relative_path}")
        else:
            skipped += 1
            print(f"[SKIP ] {relative_path}")

    print()
    print(f"Done. Written: {written}, skipped: {skipped}")
    print()
    print("Next steps:")
    print("  1. Run: python test_rts_smart_covers_project.py")
    print("  2. If tests pass, commit and push to GitHub:")
    print("     git init")
    print("     git add .")
    print('     git commit -m "Initial RTS Smart Covers integration"')
    print("     gh repo create haxxel1337/RTS-Smart-Covers --public --source . --remote origin --push")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
